- name: Start pw container
  community.docker.docker_container:
    name: "{{ pw_container_name }}"
    image: "{{ pw_image }}"
    state: started
    restart: true
    ports:
      - "{{ pw_port_mapping }}"
