- name: Create home dir
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '0700'
  with_items: "{{ pw_instances }}"
  
- name: Create docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ item.path }}/docker-compose.yml"
    mode: "0700"
  notify: restart pw
  with_items: "{{ pw_instances }}"
