- name: Start pw container
  community.docker.docker_container:
    name: "{{ item.container_name }}"
    image: "{{ item.image }}"
    state: started
    restart: true
    ports:
      - "{{ item.port_mapping }}"
  with_items: "{{ pw_instances }}"
